"""Pure candidate renderer for externally supplied Scout role research.

This source is intentionally not wired into the bundled inventory yet.  It
does not read files, fetch locators, invoke providers, or publish evidence; a
future validated Run-output adapter must supply and persist its exact bytes.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import date
import html
import re
from urllib.parse import urlsplit

from gigai.canonical import canonical_json_bytes, digest_imported_bytes


_ID = re.compile(r"^[a-z][a-z0-9_-]{1,63}$")
_GRAPH_ID = re.compile(r"^graph_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
_RUN_ID = re.compile(r"^run_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
_PROJECT_ID = re.compile(r"^project_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
_GIG_ID = re.compile(r"^gig_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
_RECORD_ID = re.compile(r"^record_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
_REVISION_ID = re.compile(r"^revision_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
_REFERENCE_ID = re.compile(r"^ref_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
_RUN_INPUT_ID = re.compile(r"^input_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
_TASK_CONTEXT_ID = re.compile(r"^task_context_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
_SHA256 = re.compile(r"^sha256:[0-9a-f]{64}$")
_CURRENCY = re.compile(r"^[A-Z]{3}$")
_ARTIFACT_ID = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,63}$")
_SOURCE_STATUS = ("reported", "captured", "independently_verified")
_SOURCE_RANK = {name: index for index, name in enumerate(_SOURCE_STATUS)}
_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_COMPENSATION_SOURCE_KINDS = {"salary_survey", "employer", "job_posting"}


class ResearchPacketError(ValueError):
    """Typed, content-free refusal for an invalid candidate research packet."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code


@dataclass(frozen=True)
class ResearchPacket:
    """Exact generated bytes and the strict sidecar that binds them."""

    markdown: bytes
    sidecar: dict[str, object]
    sidecar_bytes: bytes


def _refuse(code: str, message: str) -> None:
    raise ResearchPacketError(code, message)


def _mapping(value: object, *, name: str) -> Mapping[str, object]:
    if not isinstance(value, Mapping):
        _refuse("research_packet_invalid", f"{name} is invalid")
    return value


def _closed(value: Mapping[str, object], *, name: str, required: set[str], allowed: set[str]) -> None:
    if set(value) - allowed or not required <= set(value):
        _refuse("research_packet_invalid", f"{name} has invalid fields")


def _text(value: object, *, name: str, allow_empty: bool = False, limit: int = 4000) -> str:
    if not isinstance(value, str) or len(value) > limit or (not allow_empty and not value.strip()):
        _refuse("research_packet_invalid", f"{name} is invalid")
    if "\x00" in value or any(ord(char) < 32 and char not in "\n\t" for char in value):
        _refuse("research_packet_invalid", f"{name} is invalid")
    return value


def _id(value: object, *, name: str, pattern: re.Pattern[str] = _ID) -> str:
    if not isinstance(value, str) or not pattern.fullmatch(value):
        _refuse("research_packet_invalid", f"{name} is invalid")
    return value


def _date(value: object, *, name: str) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str) or not _DATE.fullmatch(value):
        _refuse("research_packet_invalid", f"{name} is invalid")
    try:
        date.fromisoformat(value)
    except ValueError:
        _refuse("research_packet_invalid", f"{name} is invalid")
    return value


def _locator(value: object) -> str:
    locator = _text(value, name="source locator", limit=2048)
    try:
        parsed = urlsplit(locator)
    except ValueError:
        _refuse("research_packet_invalid", "source locator is unsafe")
    if parsed.scheme not in {"http", "https"} or not parsed.netloc or parsed.username or parsed.password:
        _refuse("research_packet_invalid", "source locator is unsafe")
    if any(part == ".." for part in parsed.path.split("/")):
        _refuse("research_packet_invalid", "source locator is unsafe")
    return locator


def _artifact_ref(
    value: object,
    *,
    name: str,
    artifacts: Mapping[str, bytes],
    required: bool,
) -> dict[str, object] | None:
    if value is None:
        if required:
            _refuse("research_packet_incomplete", f"{name} is required")
        return None
    reference = _mapping(value, name=name)
    _closed(
        reference,
        name=name,
        required={"artifact_id", "content_sha256", "size_bytes"},
        allowed={"artifact_id", "content_sha256", "size_bytes"},
    )
    artifact_id = _id(reference["artifact_id"], name=f"{name} artifact")
    digest = reference["content_sha256"]
    size = reference["size_bytes"]
    if not isinstance(digest, str) or not _SHA256.fullmatch(digest) or type(size) is not int or size < 0:
        _refuse("research_packet_invalid", f"{name} is invalid")
    supplied = artifacts.get(artifact_id)
    if type(supplied) is not bytes:
        _refuse("research_packet_incomplete", f"{name} bytes are required")
    if len(supplied) != size or digest_imported_bytes(supplied) != digest:
        _refuse("research_packet_artifact_mismatch", f"{name} bytes do not match")
    return {"artifact_id": artifact_id, "content_sha256": digest, "size_bytes": size}


def _actor(value: object) -> dict[str, object]:
    actor = _mapping(value, name="verification actor")
    _closed(actor, name="verification actor", required={"kind", "id"}, allowed={"kind", "id"})
    if not isinstance(actor["kind"], str) or actor["kind"] not in {"agent", "operator", "reviewer", "tool"}:
        _refuse("research_packet_invalid", "verification actor is invalid")
    return {"kind": actor["kind"], "id": _text(actor["id"], name="verification actor id", limit=255)}


def _verification(
    value: object,
    *,
    artifacts: Mapping[str, bytes],
    capture: Mapping[str, object],
) -> dict[str, object]:
    verification = _mapping(value, name="verification")
    _closed(
        verification,
        name="verification",
        required={"method", "evidence_ref", "actor"},
        allowed={"evidence_status", "method", "evidence_ref", "actor"},
    )
    if "evidence_status" in verification and verification["evidence_status"] != "supplied":
        _refuse("research_packet_invalid", "verification evidence status is invalid")
    if (
        not isinstance(verification["method"], str)
        or verification["method"] not in {"independent_review", "manual_comparison", "signed_attestation"}
    ):
        _refuse("research_packet_invalid", "verification method is invalid")
    evidence = _artifact_ref(verification["evidence_ref"], name="verification evidence", artifacts=artifacts, required=True)
    assert evidence is not None
    if (
        evidence["artifact_id"] == capture["artifact_id"]
        or evidence["content_sha256"] == capture["content_sha256"]
    ):
        _refuse("research_packet_invalid", "verification evidence must be separate")
    return {
        "evidence_status": "supplied",
        "method": verification["method"],
        "evidence_ref": evidence,
        "actor": _actor(verification["actor"]),
    }


def _source(value: object, *, artifacts: Mapping[str, bytes]) -> dict[str, object]:
    source = _mapping(value, name="source")
    _closed(
        source,
        name="source",
        required={"source_id", "locator", "title", "publisher", "kind", "published_date", "retrieved_date", "status", "claim_ids", "capture_ref", "verification"},
        allowed={"source_id", "locator", "title", "publisher", "kind", "published_date", "retrieved_date", "status", "claim_ids", "capture_ref", "verification"},
    )
    source_id = _id(source["source_id"], name="source id")
    if source["publisher"] is not None:
        publisher = _text(source["publisher"], name="source publisher", limit=500)
    else:
        publisher = None
    if (
        not isinstance(source["kind"], str)
        or source["kind"] not in {"employer", "salary_survey", "industry", "job_posting", "government", "other"}
    ):
        _refuse("research_packet_invalid", "source kind is invalid")
    status = source["status"]
    if not isinstance(status, str) or status not in _SOURCE_STATUS:
        _refuse("research_packet_invalid", "source status is invalid")
    claim_ids = source["claim_ids"]
    if (
        not isinstance(claim_ids, list)
        or not claim_ids
        or not all(isinstance(claim_id, str) for claim_id in claim_ids)
        or len(set(claim_ids)) != len(claim_ids)
    ):
        _refuse("research_packet_invalid", "source claims are invalid")
    normalized_claims = [_id(item, name="source claim") for item in claim_ids]
    capture = _artifact_ref(source["capture_ref"], name="source capture", artifacts=artifacts, required=status != "reported")
    if status == "reported" and capture is not None:
        _refuse("research_packet_invalid", "reported source cannot carry captured bytes")
    if status == "independently_verified":
        assert capture is not None
        if source["verification"] is None:
            _refuse("research_packet_incomplete", "verification evidence is required")
        verification = _verification(source["verification"], artifacts=artifacts, capture=capture)
    else:
        if source["verification"] is not None:
            _refuse("research_packet_invalid", "unverified source cannot carry verification")
        verification = None
    return {
        "source_id": source_id,
        "locator": _locator(source["locator"]),
        "title": _text(source["title"], name="source title", limit=500),
        "publisher": publisher,
        "kind": source["kind"],
        "published_date": _date(source["published_date"], name="published date"),
        "retrieved_date": _date(source["retrieved_date"], name="retrieved date"),
        "status": status,
        "claim_ids": normalized_claims,
        "capture_ref": capture,
        "verification": verification,
    }


def _claim(value: object) -> dict[str, object]:
    claim = _mapping(value, name="claim")
    _closed(claim, name="claim", required={"claim_id", "statement", "source_ids", "status"}, allowed={"claim_id", "statement", "source_ids", "status"})
    source_ids = claim["source_ids"]
    if (
        not isinstance(source_ids, list)
        or not source_ids
        or not all(isinstance(source_id, str) for source_id in source_ids)
        or len(set(source_ids)) != len(source_ids)
    ):
        _refuse("research_packet_invalid", "claim sources are invalid")
    if not isinstance(claim["status"], str) or claim["status"] not in _SOURCE_STATUS:
        _refuse("research_packet_invalid", "claim status is invalid")
    return {
        "claim_id": _id(claim["claim_id"], name="claim id"),
        "statement": _text(claim["statement"], name="claim statement"),
        "source_ids": [_id(item, name="claim source") for item in source_ids],
        "status": claim["status"],
    }


def _items(value: object, *, name: str, fields: set[str], claim_required: bool = True) -> list[dict[str, object]]:
    if not isinstance(value, list) or not value:
        _refuse("research_packet_invalid", f"{name} is invalid")
    result: list[dict[str, object]] = []
    seen: set[str] = set()
    identifier = next(field for field in sorted(fields) if field.endswith("_id"))
    for item in value:
        mapped = _mapping(item, name=name)
        _closed(mapped, name=name, required=fields, allowed=fields)
        identity = _id(mapped[identifier], name=identifier)
        if identity in seen:
            _refuse("research_packet_invalid", f"{name} has duplicate identifiers")
        seen.add(identity)
        normalized = {identifier: identity}
        for field in sorted(fields - {identifier, "claim_ids"}):
            normalized[field] = _text(mapped[field], name=field)
        claims = mapped.get("claim_ids")
        if claims is None and claim_required:
            _refuse("research_packet_invalid", f"{name} claims are required")
        if claims is not None:
            if (
                not isinstance(claims, list)
                or (claim_required and not claims)
                or not all(isinstance(claim_id, str) for claim_id in claims)
                or len(set(claims)) != len(claims)
            ):
                _refuse("research_packet_invalid", f"{name} claims are invalid")
            normalized["claim_ids"] = [_id(item, name=f"{name} claim") for item in claims]
        result.append(normalized)
    return result


def _compensation(
    value: object,
    *,
    claim_ids: set[str],
    claim_by_id: Mapping[str, Mapping[str, object]],
    source_by_id: Mapping[str, Mapping[str, object]],
) -> dict[str, object]:
    compensation = _mapping(value, name="compensation")
    _closed(
        compensation,
        name="compensation",
        required={"status", "geography", "currency", "as_of_date", "pay_period", "base_range", "total_range", "source_limitations", "claim_ids"},
        allowed={"status", "geography", "currency", "as_of_date", "pay_period", "base_range", "total_range", "source_limitations", "claim_ids"},
    )
    status = compensation["status"]
    if not isinstance(status, str) or status not in {"unknown", "known"}:
        _refuse("research_packet_invalid", "compensation status is invalid")
    limitations = compensation["source_limitations"]
    if not isinstance(limitations, list) or not limitations:
        _refuse("research_packet_invalid", "compensation limitations are required")
    normalized_limitations = [_text(item, name="compensation limitation") for item in limitations]
    claims = compensation["claim_ids"]
    if (
        not isinstance(claims, list)
        or not all(isinstance(claim_id, str) for claim_id in claims)
        or len(set(claims)) != len(claims)
        or any(claim_id not in claim_ids for claim_id in claims)
    ):
        _refuse("research_packet_invalid", "compensation claims are invalid")

    def money_range(item: object, name: str) -> dict[str, int] | None:
        if item is None:
            return None
        item = _mapping(item, name=name)
        _closed(item, name=name, required={"minimum", "maximum"}, allowed={"minimum", "maximum"})
        if type(item["minimum"]) is not int or type(item["maximum"]) is not int or item["minimum"] < 0 or item["maximum"] < item["minimum"]:
            _refuse("research_packet_invalid", f"{name} is invalid")
        return {"minimum": item["minimum"], "maximum": item["maximum"]}

    base = money_range(compensation["base_range"], "base range")
    total = money_range(compensation["total_range"], "total range")
    if status == "unknown":
        if any(compensation[field] is not None for field in ("geography", "currency", "as_of_date", "pay_period", "base_range", "total_range")) or claims:
            _refuse("research_packet_invalid", "unknown compensation must remain explicit")
    else:
        if not all(compensation[field] is not None for field in ("geography", "currency", "as_of_date", "pay_period")) or (base is None and total is None) or not claims:
            _refuse("research_packet_incomplete", "known compensation lacks required context")
        if (
            not isinstance(compensation["currency"], str)
            or _CURRENCY.fullmatch(compensation["currency"]) is None
            or not isinstance(compensation["pay_period"], str)
            or compensation["pay_period"] not in {"annual", "monthly", "weekly", "hourly"}
        ):
            _refuse("research_packet_invalid", "compensation context is invalid")
        if base is not None and total is not None and (
            total["minimum"] < base["minimum"] or total["maximum"] < base["maximum"]
        ):
            _refuse("research_packet_invalid", "compensation total is incoherent with base")
        for claim_id in claims:
            claim_sources = claim_by_id[str(claim_id)]["source_ids"]
            if not any(
                source_by_id[str(source_id)]["kind"] in _COMPENSATION_SOURCE_KINDS
                for source_id in claim_sources
            ):
                _refuse("research_packet_invalid", "compensation claims lack declared salary evidence")
    return {
        "status": status,
        "geography": None if compensation["geography"] is None else _text(compensation["geography"], name="compensation geography"),
        "currency": compensation["currency"],
        "as_of_date": _date(compensation["as_of_date"], name="compensation as-of date"),
        "pay_period": compensation["pay_period"],
        "base_range": base,
        "total_range": total,
        "source_limitations": normalized_limitations,
        "claim_ids": list(claims),
    }


def _input_artifact(value: object, *, name: str) -> dict[str, object]:
    reference = _mapping(value, name=name)
    _closed(
        reference,
        name=name,
        required={"path", "content_sha256", "media_type", "size_bytes"},
        allowed={"path", "content_sha256", "media_type", "size_bytes"},
    )
    path = reference["path"]
    digest = reference["content_sha256"]
    media_type = reference["media_type"]
    size = reference["size_bytes"]
    if (
        not isinstance(path, str)
        or not path
        or len(path) > 512
        or "\\" in path
        or any(part in {"", ".", ".."} for part in path.split("/"))
        or path.split("/", 1)[0] not in {"records", "references", "run-inputs", "docs"}
        or not isinstance(digest, str)
        or _SHA256.fullmatch(digest) is None
        or not isinstance(media_type, str)
        or not media_type
        or len(media_type) > 120
        or type(size) is not int
        or size < 0
    ):
        _refuse("research_packet_invalid", f"{name} is invalid")
    return {
        "path": path,
        "content_sha256": digest,
        "media_type": media_type,
        "size_bytes": size,
    }


def _g45_input(value: object) -> dict[str, object]:
    item = _mapping(value, name="G45 selected input")
    family = item.get("family")
    identifier = "reference_id" if family == "g45_reference" else "run_input_id"
    pattern = _REFERENCE_ID if family == "g45_reference" else _RUN_INPUT_ID
    if family not in {"g45_reference", "g45_run_input"}:
        _refuse("research_packet_invalid", "G45 selected input is invalid")
    _closed(
        item,
        name="G45 selected input",
        required={"family", identifier, "record_ref", "snapshot_ref"},
        allowed={"family", identifier, "record_ref", "snapshot_ref"},
    )
    return {
        "family": family,
        identifier: _id(item[identifier], name="G45 selected input identity", pattern=pattern),
        "record_ref": _input_artifact(item["record_ref"], name="G45 record ref"),
        "snapshot_ref": _input_artifact(item["snapshot_ref"], name="G45 snapshot ref"),
    }


def _native_scope(value: object) -> dict[str, object]:
    scope = _mapping(value, name="native selected input scope")
    _closed(
        scope,
        name="native selected input scope",
        required={"mode", "task_context_id", "base"},
        allowed={"mode", "task_context_id", "base"},
    )
    if scope == {"mode": "saved_default", "task_context_id": None, "base": None}:
        return dict(scope)
    base = _mapping(scope["base"], name="native selected input base")
    _closed(
        base,
        name="native selected input base",
        required={"record_id", "revision_id"},
        allowed={"record_id", "revision_id"},
    )
    if scope["mode"] != "run_override":
        _refuse("research_packet_invalid", "native selected input scope is invalid")
    return {
        "mode": "run_override",
        "task_context_id": _id(
            scope["task_context_id"],
            name="native selected input task context",
            pattern=_TASK_CONTEXT_ID,
        ),
        "base": {
            "record_id": _id(base["record_id"], name="native selected input base record", pattern=_RECORD_ID),
            "revision_id": _id(base["revision_id"], name="native selected input base revision", pattern=_REVISION_ID),
        },
    }


def _native_blob(value: object) -> dict[str, object]:
    blob = _mapping(value, name="native selected input content")
    _closed(
        blob,
        name="native selected input content",
        required={"family", "blob_ref", "content_sha256"},
        allowed={"family", "blob_ref", "content_sha256"},
    )
    digest = blob["content_sha256"]
    if blob["family"] != "jsl_blob" or not isinstance(digest, str) or _SHA256.fullmatch(digest) is None:
        _refuse("research_packet_invalid", "native selected input content is invalid")
    return {
        "family": "jsl_blob",
        "blob_ref": _input_artifact(blob["blob_ref"], name="native selected input blob ref"),
        "content_sha256": digest,
    }


def _selected_input(value: object) -> dict[str, object]:
    item = _mapping(value, name="selected input")
    family = item.get("family")
    if family == "role_request":
        _closed(
            item,
            name="role request",
            required={"family", "role_title", "role_context"},
            allowed={"family", "role_title", "role_context"},
        )
        context = item["role_context"]
        if context is not None:
            context = _text(context, name="role context", limit=4096)
        return {
            "family": "role_request",
            "role_title": _text(item["role_title"], name="role title", limit=300),
            "role_context": context,
        }
    if family in {"g45_reference", "g45_run_input"}:
        return _g45_input(item)
    if family != "scout_record":
        _refuse("research_packet_invalid", "selected input family is invalid")
    content = item.get("content")
    if not isinstance(content, Mapping):
        _refuse("research_packet_invalid", "Scout selected input content is invalid")
    normalized_content_family = content.get("family")
    if normalized_content_family in {"g45_reference", "g45_run_input"}:
        _closed(
            item,
            name="Scout G45 selected input",
            required={"family", "record_id", "revision_id", "content"},
            allowed={"family", "record_id", "revision_id", "content"},
        )
        return {
            "family": "scout_record",
            "record_id": _id(item["record_id"], name="Scout selected input record", pattern=_RECORD_ID),
            "revision_id": _id(item["revision_id"], name="Scout selected input revision", pattern=_REVISION_ID),
            "content": _g45_input(content),
        }
    _closed(
        item,
        name="Scout native selected input",
        required={"family", "record_id", "revision_id", "native_kind", "scope", "content"},
        allowed={"family", "record_id", "revision_id", "native_kind", "scope", "content"},
    )
    if item["native_kind"] not in {"profile_preferences", "experience_qa"}:
        _refuse("research_packet_invalid", "Scout native selected input kind is invalid")
    return {
        "family": "scout_record",
        "record_id": _id(item["record_id"], name="Scout selected input record", pattern=_RECORD_ID),
        "revision_id": _id(item["revision_id"], name="Scout selected input revision", pattern=_REVISION_ID),
        "native_kind": item["native_kind"],
        "scope": _native_scope(item["scope"]),
        "content": _native_blob(content),
    }


def _selected_inputs(value: Sequence[Mapping[str, object]]) -> list[dict[str, object]]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)) or not value:
        _refuse("research_packet_incomplete", "selected role input is required")
    result: list[dict[str, object]] = []
    seen: set[bytes] = set()
    for item in value:
        normalized = _selected_input(item)
        identity = canonical_json_bytes(normalized)
        if identity in seen:
            _refuse("research_packet_invalid", "selected inputs are invalid")
        seen.add(identity)
        result.append(normalized)
    if sum(item.get("family") == "role_request" for item in result) != 1:
        _refuse("research_packet_incomplete", "selected role input is required")
    return result


def _markdown(value: str) -> str:
    # Every supplied text value remains data inside one Markdown line.  Visible
    # glyphs retain line/tab intent without letting text open a Markdown block.
    inline = value.replace("\r\n", "\n").replace("\r", "\n").replace("\n", " ↵ ").replace("\t", " ⇥ ")
    escaped = html.escape(inline, quote=False).replace("\\", "\\\\")
    for character in "[]()!*`#>+-":
        escaped = escaped.replace(character, "\\" + character)
    return escaped


def _input_label(value: Mapping[str, object]) -> str:
    family = value["family"]
    if family == "role_request":
        return f"role_request {_markdown(str(value['role_title']))}"
    if family == "g45_reference":
        return f"g45_reference {value['reference_id']}"
    if family == "g45_run_input":
        return f"g45_run_input {value['run_input_id']}"
    content = value["content"]
    assert isinstance(content, Mapping)
    if content["family"] == "g45_reference":
        return f"scout_record {value['record_id']} {value['revision_id']} g45_reference {content['reference_id']}"
    if content["family"] == "g45_run_input":
        return f"scout_record {value['record_id']} {value['revision_id']} g45_run_input {content['run_input_id']}"
    return f"scout_record {value['record_id']} {value['revision_id']} {value['native_kind']}"


def _render(
    research: Mapping[str, object],
    *,
    origin: Mapping[str, object],
    selected_inputs: Sequence[Mapping[str, object]],
) -> bytes:
    lines = [
        f"# Role research: {_markdown(str(research['role_title']))}",
        "",
        "## Packet binding",
        f"Graph: {origin['graph_selector']} {origin['graph_id']} version {origin['graph_version']}; Run: {origin['run_id']}.",
        "Selected inputs: " + "; ".join(_input_label(item) for item in selected_inputs),
        "",
        "## Role summary",
        _markdown(str(research["role_summary"])),
        "",
        "## Responsibilities",
    ]
    for item in research["responsibilities"]:
        lines.append(f"- {item['responsibility_id']}: {_markdown(str(item['description']))} (declared claims: {', '.join(item['claim_ids'])})")
    lines.extend(["", "## Role variations"])
    for item in research["variations"]:
        lines.append(f"- {item['variation_id']}: {_markdown(str(item['description']))} (declared claims: {', '.join(item['claim_ids'])})")
    lines.extend(["", "## Reusable sections"])
    for item in research["reusable_sections"]:
        lines.extend([
            f"### {item['section_id']}: {_markdown(str(item['heading']))}",
            _markdown(str(item['content'])),
            f"Declared claims: {', '.join(item['claim_ids'])}",
            "",
        ])
    compensation = research["compensation"]
    lines.extend(["## Compensation"])
    if compensation["status"] == "unknown":
        lines.append("Compensation is unknown. " + _markdown("; ".join(compensation["source_limitations"])))
    else:
        lines.append(f"Geography: {_markdown(str(compensation['geography']))}; currency: {compensation['currency']}; as of: {compensation['as_of_date']}; period: {compensation['pay_period']}.")
        for name, item in (("Base", compensation["base_range"]), ("Total", compensation["total_range"])):
            if item is not None:
                lines.append(f"{name}: {item['minimum']}–{item['maximum']} {compensation['currency']}.")
        lines.append("Limitations: " + _markdown("; ".join(compensation["source_limitations"])))
        lines.append("Declared compensation claims: " + ", ".join(compensation["claim_ids"]))
    lines.extend(["", "## Sources"])
    for source in research["sources"]:
        publisher = source["publisher"] or "unknown publisher"
        verification_label = "; supplied verification evidence (actor recorded in sidecar)" if source["verification"] else ""
        capture = source["capture_ref"]
        capture_label = "no capture bytes" if capture is None else f"capture: {capture['artifact_id']} {capture['content_sha256']}"
        verification = source["verification"]
        verification_detail = ""
        if verification is not None:
            evidence = verification["evidence_ref"]
            actor = verification["actor"]
            verification_detail = (
                f"; supplied verification: {verification['method']}; evidence: "
                f"{evidence['artifact_id']} {evidence['content_sha256']}; "
                f"actor: {_markdown(str(actor['kind']))}/{_markdown(str(actor['id']))}"
            )
        lines.append(
            f"- {source['source_id']}: {_markdown(str(source['title']))} — {_markdown(str(publisher))}; "
            f"{source['kind']}; {source['status']}{verification_label}; "
            f"published: {source['published_date']}; retrieved: {source['retrieved_date']}; "
            f"declared claims: {', '.join(source['claim_ids'])}; {capture_label}{verification_detail}; "
            f"locator: {_markdown(str(source['locator']))}"
        )
    lines.extend(["", "## Claims"])
    for claim in research["claims"]:
        lines.append(
            f"- {claim['claim_id']}: {_markdown(str(claim['statement']))}; "
            f"declared {claim['status']}; sources: {', '.join(claim['source_ids'])}"
        )
    lines.extend(["", "## Uncertainties"])
    for item in research["uncertainties"]:
        lines.append(
            f"- {item['uncertainty_id']}: {_markdown(str(item['topic']))}: {_markdown(str(item['detail']))} "
            f"(declared claims: {', '.join(item['claim_ids'])})"
        )
    lines.extend(["", "## Focused questions"])
    for item in research["questions"]:
        lines.append(
            f"- {item['question_id']}: {_markdown(str(item['prompt']))} — {_markdown(str(item['reason']))} "
            f"(declared claims: {', '.join(item['claim_ids'])})"
        )
    lines.extend(["", "## Declared checks"])
    for item in research["checks"]:
        lines.append(
            f"- {item['check_id']}: {item['kind']}: {item['result']}; {_markdown(str(item['detail']))} "
            f"(declared claims: {', '.join(item['claim_ids'])})"
        )
    lines.extend(["", "## Reuse roles", ", ".join(research["output_roles"]), ""])
    return "\n".join(lines).encode("utf-8")


def build_research_packet(
    *,
    project_id: str,
    gig_id: str,
    gig_version: int,
    graph_id: str,
    graph_version: int,
    run_id: str,
    selected_inputs: Sequence[Mapping[str, object]],
    research: Mapping[str, object],
    artifact_bytes: Mapping[str, bytes],
) -> ResearchPacket:
    """Validate and render supplied role research without any I/O or execution."""

    project_id = _id(project_id, name="project id", pattern=_PROJECT_ID)
    gig_id = _id(gig_id, name="Gig id", pattern=_GIG_ID)
    if type(gig_version) is not int or gig_version < 1:
        _refuse("research_packet_invalid", "Gig version is invalid")
    graph_id = _id(graph_id, name="graph id", pattern=_GRAPH_ID)
    run_id = _id(run_id, name="run id", pattern=_RUN_ID)
    if type(graph_version) is not int or graph_version < 1:
        _refuse("research_packet_invalid", "graph version is invalid")
    if not isinstance(artifact_bytes, Mapping):
        _refuse("research_packet_invalid", "artifact bytes are invalid")
    for key, value in artifact_bytes.items():
        if (
            not isinstance(key, str)
            or _ARTIFACT_ID.fullmatch(key) is None
            or type(value) is not bytes
        ):
            _refuse("research_packet_invalid", "artifact bytes are invalid")
    inputs = _selected_inputs(selected_inputs)
    research = _mapping(research, name="research")
    _closed(
        research,
        name="research",
        required={"role_title", "role_summary", "responsibilities", "variations", "reusable_sections", "compensation", "sources", "claims", "uncertainties", "questions", "checks", "output_roles"},
        allowed={"role_title", "role_summary", "responsibilities", "variations", "reusable_sections", "compensation", "sources", "claims", "uncertainties", "questions", "checks", "output_roles"},
    )
    claims = [_claim(item) for item in research["claims"]] if isinstance(research["claims"], list) else []
    if not claims or len({item["claim_id"] for item in claims}) != len(claims):
        _refuse("research_packet_invalid", "claims are invalid")
    claim_by_id = {str(item["claim_id"]): item for item in claims}
    sources = [_source(item, artifacts=artifact_bytes) for item in research["sources"]] if isinstance(research["sources"], list) else []
    if not sources or len({item["source_id"] for item in sources}) != len(sources):
        _refuse("research_packet_invalid", "sources are invalid")
    source_by_id = {str(item["source_id"]): item for item in sources}
    for claim in claims:
        for source_id in claim["source_ids"]:
            source = source_by_id.get(str(source_id))
            if source is None or claim["claim_id"] not in source["claim_ids"] or _SOURCE_RANK[str(source["status"])] < _SOURCE_RANK[str(claim["status"])]:
                _refuse("research_packet_invalid", "claim/source relationships are invalid")
    for source in sources:
        for claim_id in source["claim_ids"]:
            claim = claim_by_id.get(str(claim_id))
            if claim is None or source["source_id"] not in claim["source_ids"]:
                _refuse("research_packet_invalid", "claim/source relationships are invalid")
    responsibilities = _items(research["responsibilities"], name="responsibilities", fields={"responsibility_id", "description", "claim_ids"})
    variations = _items(research["variations"], name="variations", fields={"variation_id", "description", "claim_ids"})
    reusable = _items(research["reusable_sections"], name="reusable sections", fields={"section_id", "heading", "content", "claim_ids"})
    uncertainties = _items(research["uncertainties"], name="uncertainties", fields={"uncertainty_id", "topic", "detail", "claim_ids"}, claim_required=False)
    questions = _items(research["questions"], name="questions", fields={"question_id", "prompt", "reason", "claim_ids"}, claim_required=False)
    checks = _items(research["checks"], name="checks", fields={"check_id", "kind", "result", "detail", "claim_ids"}, claim_required=False)
    if any(item["kind"] not in {"schema", "source_integrity", "relationship"} or item["result"] not in {"pass", "warning"} for item in checks):
        _refuse("research_packet_invalid", "checks are invalid")
    for collection in (responsibilities, variations, reusable, uncertainties, questions, checks):
        for item in collection:
            if any(claim_id not in claim_by_id for claim_id in item.get("claim_ids", [])):
                _refuse("research_packet_invalid", "domain item has dangling claims")
    roles = research["output_roles"]
    if (
        not isinstance(roles, list)
        or not roles
        or not all(isinstance(role, str) for role in roles)
        or len(set(roles)) != len(roles)
        or any(role not in {"tailoring_context", "interview_context", "role_research"} for role in roles)
    ):
        _refuse("research_packet_invalid", "output roles are invalid")
    normalized: dict[str, object] = {
        "role_title": _text(research["role_title"], name="role title", limit=300),
        "role_summary": _text(research["role_summary"], name="role summary"),
        "responsibilities": responsibilities,
        "variations": variations,
        "reusable_sections": reusable,
        "compensation": _compensation(
            research["compensation"],
            claim_ids=set(claim_by_id),
            claim_by_id=claim_by_id,
            source_by_id=source_by_id,
        ),
        "sources": sources,
        "claims": claims,
        "uncertainties": uncertainties,
        "questions": questions,
        "checks": checks,
        "output_roles": list(roles),
    }
    role_request = next(item for item in inputs if item["family"] == "role_request")
    if normalized["role_title"] != role_request["role_title"]:
        _refuse("research_packet_invalid", "research role title does not match the sealed role request")
    origin = {
        "project_id": project_id,
        "gig_id": gig_id,
        "gig_version": gig_version,
        "graph_selector": "research-role",
        "graph_id": graph_id,
        "graph_version": graph_version,
        "run_id": run_id,
    }
    markdown = _render(normalized, origin=origin, selected_inputs=inputs)
    sidecar: dict[str, object] = {
        "schema_version": "scout-research-sidecar:2",
        "output_kind": "role_research",
        "output_roles": list(roles),
        "document_sha256": digest_imported_bytes(markdown),
        "document_size_bytes": len(markdown),
        "origin": origin,
        "selected_inputs": inputs,
        "research": normalized,
    }
    return ResearchPacket(markdown=markdown, sidecar=sidecar, sidecar_bytes=canonical_json_bytes(sidecar))


def validate_rendered_packet(
    *,
    markdown: bytes,
    sidecar: Mapping[str, object],
    artifact_bytes: Mapping[str, bytes],
) -> None:
    """Revalidate supplied evidence and require canonical domain rendering in memory.

    The validator rebuilds once from the sealed sidecar; the builder never calls
    this function, so this is deliberately not a recursive render/validate loop.
    """

    sidecar = _mapping(sidecar, name="research sidecar")
    _closed(sidecar, name="research sidecar", required={"schema_version", "output_kind", "output_roles", "document_sha256", "document_size_bytes", "origin", "selected_inputs", "research"}, allowed={"schema_version", "output_kind", "output_roles", "document_sha256", "document_size_bytes", "origin", "selected_inputs", "research"})
    if sidecar["schema_version"] != "scout-research-sidecar:2" or sidecar["output_kind"] != "role_research" or type(markdown) is not bytes or sidecar["document_sha256"] != digest_imported_bytes(markdown) or sidecar["document_size_bytes"] != len(markdown):
        _refuse("research_packet_digest_mismatch", "research document binding is invalid")
    origin = _mapping(sidecar["origin"], name="research origin")
    _closed(
        origin,
        name="research origin",
        required={"project_id", "gig_id", "gig_version", "graph_selector", "graph_id", "graph_version", "run_id"},
        allowed={"project_id", "gig_id", "gig_version", "graph_selector", "graph_id", "graph_version", "run_id"},
    )
    if origin["graph_selector"] != "research-role":
        _refuse("research_packet_invalid", "research origin is invalid")
    rebuilt = build_research_packet(
        project_id=str(origin["project_id"]),
        gig_id=str(origin["gig_id"]),
        gig_version=origin["gig_version"],
        graph_id=str(origin["graph_id"]),
        graph_version=origin["graph_version"],
        run_id=str(origin["run_id"]),
        selected_inputs=sidecar["selected_inputs"],
        research=sidecar["research"],
        artifact_bytes=artifact_bytes,
    )
    if rebuilt.markdown != markdown:
        _refuse("research_packet_render_mismatch", "research document does not match sealed data")
    if rebuilt.sidecar != sidecar:
        _refuse("research_packet_invalid", "research sidecar is not canonical")


__all__ = ["ResearchPacket", "ResearchPacketError", "build_research_packet", "validate_rendered_packet"]
