"""Generate the reference pages of the public docs site (``gigai-docs/``).

One small generator, four outputs, all derived from the code so they cannot drift:

* ``reference/cli.md``        core commands, from 0110-008's CLI manual (``gigai agent-context``:
                               shipped commands.yaml merged with the live Click tree)
* ``scout/reference/cli.md``  the ``gigai scout ...`` commands, same source
* ``changelog.md``            ``CHANGELOG.md`` with front matter (release notes already
                               come from the same file via tools/release_notes.py)
* ``generated/scout-openapi.json``  the Scout API spec (0110-007 ``openapi_document()``, no server
                               needed), rendered by starlight-openapi

``--check`` regenerates in memory and exits 1 when a committed file differs (the CI
"generated reference is stale" gate, like scout-ui-freshness). It also enforces the docs
boundary that mirrors the code boundary: pages outside ``scout/`` link into ``scout/``
only from ``index.md``, so Scout's section can move to Scout's own repo cleanly.

Usage (from the repo root)::

    uv run --locked python tools/docs_gen.py            # write
    uv run --locked python tools/docs_gen.py --check    # CI
"""

from __future__ import annotations

import argparse
import json
import posixpath
import re
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DOCS = REPO / "gigai-docs" / "src" / "content" / "docs"
GENERATED = REPO / "gigai-docs" / "src" / "content" / "generated"
MARK = "<!-- GENERATED by tools/docs_gen.py. Do not edit; run `make docs-gen`. -->"


# --------------------------------------------------------------------------- CLI
def cli_pages() -> dict[str, str]:
    """The CLI manual (0110-008: shipped commands.yaml + the live Click tree), split core / Scout.

    Reuses 0110-008's own Markdown renderer, so the site and ``gigai agent-context`` say the
    same thing. Hidden commands stay out of the public site (they are in ``--json``).
    """
    from gigai.agent_context import build_manual, render_markdown
    from gigai.cli import cli

    manual = build_manual(cli)
    public = [c for c in manual["commands"] if not c["hidden"]]
    pages = {
        "reference/cli.md": ("CLI reference", "Every core gigai command.", [c for c in public if c["path"][0] != "scout"]),
        "scout/reference/cli.md": ("Scout CLI reference", "Every gigai scout command.", [c for c in public if c["path"][0] == "scout"]),
    }
    out = {}
    for rel, (title, description, commands) in pages.items():
        body = render_markdown({**manual, "commandCount": len(commands), "commands": commands})
        body = body.split("\n", 1)[1].lstrip()  # drop its H1; the site renders the title
        body = body.replace("Generated by `make cli-manual` from `gigai agent-context`; do not edit by hand.\n", "")
        out[rel] = "\n".join(["---", f"title: {title}", f"description: {description}", "---", "", MARK, "", body])
    return out


# --------------------------------------------------------------------- changelog
def render_changelog(src: str) -> str:
    body = re.sub(r"<!--.*?-->", "", src, flags=re.S)
    body = re.sub(r"\A# .*\n", "", body.lstrip())
    body = re.sub(r"\n{3,}", "\n\n", body).strip()
    head = ["---", "title: Changelog", "description: What changed in each GigAI release.", "---", "", MARK, ""]
    return "\n".join(head) + body + "\n"


# ----------------------------------------------------------------------- OpenAPI
def scout_openapi() -> str | None:
    try:
        from gigai.scout.find_jobs.api.openapi import openapi_document  # 0110-007
    except ImportError:
        return None  # a version without the spec simply has no API page
    # pyproject, not installed metadata: an editable install's metadata goes stale on a bump.
    version = tomllib.loads((REPO / "pyproject.toml").read_text())["project"]["version"]
    return json.dumps(openapi_document(version=version), indent=2, sort_keys=True) + "\n"


# ---------------------------------------------------------------------- boundary
LINK = re.compile(r"\]\(([^)\s#]+)")


def boundary_violations(docs: Path | None = None) -> list[str]:
    docs = docs or DOCS
    bad = []
    for md in sorted(docs.rglob("*.md")):
        rel = md.relative_to(docs).as_posix()
        if rel.startswith("scout/") or rel == "index.md":
            continue
        page = "/" + rel.removesuffix(".md").removesuffix("index") + "/"
        for target in LINK.findall(md.read_text()):
            if re.match(r"^[a-z]+:", target):
                continue
            url = posixpath.normpath(posixpath.join(page, target))
            if url == "/scout" or url.startswith("/scout/"):
                bad.append(f"{rel}: links into scout/ ({target}); link Gigs only from index.md")
    return bad


# -------------------------------------------------------------------------- main
def outputs() -> dict[Path, str]:
    files = {DOCS / rel: text for rel, text in cli_pages().items()}
    files[DOCS / "changelog.md"] = render_changelog((REPO / "CHANGELOG.md").read_text())
    spec = scout_openapi()
    if spec is not None:
        files[GENERATED / "scout-openapi.json"] = spec
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the reference pages of gigai-docs/.")
    ap.add_argument("--check", action="store_true", help="fail if committed pages are stale")
    args = ap.parse_args()

    problems = boundary_violations()
    for path, text in outputs().items():
        rel = path.relative_to(REPO)
        if args.check:
            if not path.exists() or path.read_text() != text:
                problems.append(f"{rel} is stale; run `make docs-gen` and commit the result")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {rel}")
    for p in problems:
        print(f"::error::{p}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
